#define n_cook 2
#define n_oven 15
#define n_packer 2
#define n_deliverer 10
#define t_orderlow 1
#define t_orderhigh 3
#define n_orderlow 1
#define n_orderhigh 5
#define p_plain 0.6
#define t_paymentlow 1
#define t_paymenthigh 3
#define p_fail 0.1
#define c_plain 10
#define c_special 12
#define t_prep 1
#define t_bake 10
#define t_pack 1
#define t_deliverylow 5
#define t_deliveryhigh 15